language: python

python:
  - "3.8"

services:
  - docker

before_install:
  #- docker build -t zunware/test ./src/integration-test
  #- docker run -d zunware/test /bin/sh -c "busted main_spec.moon"
  #- docker ps -a
  - docker-compose build
  - docker-compose ps

script:
  - busted main_spec.moon