sudo: required

services:
  - docker

before_install:
  #- docker build -t zunware/test ./src/integration-test
  #- docker run -d zunware/test /bin/sh -c "busted main_spec.moon"
  #- docker ps -a
  - docker-compose up -d --build
  - docker-compose ps

script:
  - docker run fragata_tests
  - docker-compose exec fragata_django python manage.py test

after_script:
  - docker-compose down
