apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    zone: prod
    name: myapp
    version: v1
spec:
  containers:
  - name: myapp
    image: zunware/moon
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
