apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fragata-store
  namespace: fragata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi
