apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: fragata
spec:
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: zunware/postgis:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: fragata
spec:
  ports:
  - port: 5432
  selector:
    app: postgis
